package tk.packattk.components;

import java.util.Collection;

import tk.packattk.utils.Package;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.event.FieldEvents.TextChangeEvent;
import com.vaadin.event.FieldEvents.TextChangeListener;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class AdminScanOutRemovePanel extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private Table remove_table;
	@AutoGenerated
	private TextField barcode_field;
	
	private BeanItemContainer<Package> packageContainer;
	private AdminScanOutAvailablePanel availablePanel;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public AdminScanOutRemovePanel(AdminScanOutAvailablePanel _availablePanel) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		availablePanel = _availablePanel;
		
		packageContainer = new BeanItemContainer<Package>(Package.class);
		remove_table.setContainerDataSource(packageContainer);
		remove_table.setVisibleColumns("tracking", "location", "name");
		remove_table.setColumnHeaders("Tracking #", "Location", "Name");
		
		barcode_field.addTextChangeListener(new TextChangeListener() {
			@Override
			public void textChange(TextChangeEvent event) {
				String tracking = event.getText();
				Package p = availablePanel.checkOutPackage(tracking);
				if(p != null) {
					packageContainer.addBean(p);
					barcode_field.setValue("");
				}
			}
		});
	}
	
	public Collection<Package> getPackagesToRemove() {
		return packageContainer.getItemIds();
	}
	
	public void clear() {
		packageContainer.removeAllItems();
		barcode_field.setValue("");
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		mainLayout.addComponent(verticalLayout_1, "top:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("100.0%");
		verticalLayout_1.setHeight("-1px");
		verticalLayout_1.setMargin(false);
		
		// barcode_field
		barcode_field = new TextField();
		barcode_field.setCaption("Scan Barcode Here");
		barcode_field.setImmediate(false);
		barcode_field.setWidth("100.0%");
		barcode_field.setHeight("-1px");
		verticalLayout_1.addComponent(barcode_field);
		
		// remove_table
		remove_table = new Table();
		remove_table.setImmediate(false);
		remove_table.setWidth("100.0%");
		remove_table.setHeight("-1px");
		verticalLayout_1.addComponent(remove_table);
		
		return verticalLayout_1;
	}

}
