package tk.packattk.components;

import java.util.ArrayList;
import java.util.Collection;
import java.util.UUID;

import tk.packattk.components.listeners.PackageSelectListener;
import tk.packattk.utils.Package;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.util.BeanItem;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.event.ShortcutAction.KeyCode;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class AdminScanPanel extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;

	@AutoGenerated
	private VerticalLayout verticalLayout_1;

	@AutoGenerated
	private Table scanned_table;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;

	@AutoGenerated
	private Button add_button;

	@AutoGenerated
	private Button generate_button;

	@AutoGenerated
	private TextField number_scan_field;

	private BeanItemContainer<tk.packattk.utils.Package> packageContainer;
	private PackageSelectListener selectListener = null;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public AdminScanPanel() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		packageContainer = new BeanItemContainer<tk.packattk.utils.Package>(tk.packattk.utils.Package.class);
		scanned_table.setContainerDataSource(packageContainer);
		scanned_table.setVisibleColumns("tracking", "location", "name");
		scanned_table.setColumnHeaders("Tracking #", "Location", "Name");

		add_button.addClickListener(new ClickListener() {
			@Override
			public void buttonClick(ClickEvent event) {
				tk.packattk.utils.Package newPackage = new tk.packattk.utils.Package("", number_scan_field.getValue(), "Shreve", "", null, null, System.currentTimeMillis());
				packageContainer.addBean(newPackage);
				number_scan_field.setValue("");
				number_scan_field.focus();
			}
		});
		add_button.setClickShortcut(KeyCode.ENTER);

		generate_button.addClickListener(new ClickListener() {
			@Override
			public void buttonClick(ClickEvent event) {
				String genId = "PTK-" + UUID.randomUUID().toString().substring(24).toUpperCase();
				tk.packattk.utils.Package newPackage = new tk.packattk.utils.Package("", genId, "Shreve", "", null, null, System.currentTimeMillis());
				packageContainer.addBean(newPackage);
				number_scan_field.setValue("");
				number_scan_field.focus();
			}
		});

		scanned_table.setSelectable(true);
		scanned_table.setImmediate(true);
		scanned_table.addValueChangeListener(new ValueChangeListener() {
			@Override
			public void valueChange(ValueChangeEvent event) {
				tk.packattk.utils.Package p = (tk.packattk.utils.Package) scanned_table.getValue();
				if(selectListener != null) {
					selectListener.packageSelected(packageContainer.getItem(p));
				}
			}
		});
	}

	public Collection<tk.packattk.utils.Package> getPackages() {
		// Clone packages so that we aren't messing up these objects too badly
		ArrayList<tk.packattk.utils.Package> packages = new ArrayList<tk.packattk.utils.Package>();
		for(tk.packattk.utils.Package p : packageContainer.getItemIds()) {
			packages.add(p);
		}
		return packages;
	}

	public void removePackage(BeanItem<Package> currentPackage) {
		packageContainer.removeItem(currentPackage.getBean());
	}

	public void clear() {
		packageContainer.removeAllItems();
	}

	public void focusScanField() {
		number_scan_field.focus();
	}

	public void setPackageSelectListener(PackageSelectListener listener) {
		selectListener = listener;
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		mainLayout.addComponent(verticalLayout_1, "top:0.0px;left:0.0px;");

		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("100.0%");
		verticalLayout_1.setHeight("-1px");
		verticalLayout_1.setMargin(false);

		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		verticalLayout_1.addComponent(horizontalLayout_1);

		// scanned_table
		scanned_table = new Table();
		scanned_table.setCaption("Scanned");
		scanned_table.setImmediate(false);
		scanned_table.setWidth("100.0%");
		scanned_table.setHeight("-1px");
		verticalLayout_1.addComponent(scanned_table);
		verticalLayout_1.setExpandRatio(scanned_table, 1.0f);

		return verticalLayout_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("100.0%");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);

		// number_scan_field
		number_scan_field = new TextField();
		number_scan_field.setCaption("Tracking Number");
		number_scan_field.setImmediate(false);
		number_scan_field.setWidth("100.0%");
		number_scan_field.setHeight("-1px");
		horizontalLayout_1.addComponent(number_scan_field);
		horizontalLayout_1.setExpandRatio(number_scan_field, 1.0f);
		horizontalLayout_1.setComponentAlignment(number_scan_field,
				new Alignment(9));

		// generate_button
		generate_button = new Button();
		generate_button.setCaption("Generate");
		generate_button.setImmediate(true);
		generate_button.setWidth("-1px");
		generate_button.setHeight("-1px");
		horizontalLayout_1.addComponent(generate_button);
		horizontalLayout_1.setComponentAlignment(generate_button,
				new Alignment(10));

		// add_button
		add_button = new Button();
		add_button.setCaption("Add");
		add_button.setImmediate(true);
		add_button.setWidth("-1px");
		add_button.setHeight("-1px");
		horizontalLayout_1.addComponent(add_button);
		horizontalLayout_1.setComponentAlignment(add_button, new Alignment(10));

		return horizontalLayout_1;
	}

}
