package tk.packattk.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.validator.StringLengthValidator;
import com.vaadin.event.ShortcutAction.KeyCode;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;

public class LoginWindow extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private static final long serialVersionUID = 1L;
	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button login;
	@AutoGenerated
	private PasswordField password;
	@AutoGenerated
	private TextField username;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public LoginWindow() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		login.setClickShortcut(KeyCode.ENTER);
		username.addValidator(new StringLengthValidator("Username cannot be blank", 1, null, false));
	}

	public void addLoginListener(ClickListener listener) {
		login.addClickListener(listener);
	}

	public String getUsername() {
		return username.getValue();
	}

	public TextField getUsernameField() {
		return username;
	}

	public String getPassword() {
		return password.getValue();
	}

	public PasswordField getPasswordField() {
		return password;
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// username
		username = new TextField();
		username.setCaption("Username");
		username.setImmediate(false);
		username.setDescription("Username");
		username.setWidth("100.0%");
		username.setHeight("-1px");
		username.setInvalidAllowed(false);
		username.setRequired(true);
		username.setInputPrompt("Username");
		mainLayout.addComponent(username, "top:16.0px;left:0.0px;");
		
		// password
		password = new PasswordField();
		password.setCaption("Password");
		password.setImmediate(false);
		password.setDescription("Password");
		password.setWidth("100.0%");
		password.setHeight("-1px");
		password.setInvalidAllowed(false);
		password.setRequired(true);
		password.setInputPrompt("Password");
		mainLayout.addComponent(password, "top:80.0px;left:0.0px;");
		
		// login
		login = new Button();
		login.setCaption("Log In");
		login.setImmediate(true);
		login.setDescription("Log In");
		login.setWidth("100.0%");
		login.setHeight("-1px");
		mainLayout.addComponent(login, "top:144.0px;left:0.0px;");
		
		return mainLayout;
	}

}
